### ISSUE TITLE
Show a popup if the autoUpdater finds a new version

### ISSUE THREAD

**Issue by mrceresa** [bcn-medtech/reImagineClient#11]
For now you have to check in the console logs

**Comment by bcnmedtech** [comment]
Implementado, habria que probarlo, hay una nueva pagina que se deberia abrir si se ha descargado la nueva version

**Comment by mrceresa** [comment]
Genial! 

Fixed en e547e5ffd64deefe9e84fe12d28c947e4cdc145f
