### ISSUE TITLE
[BUG] Form colors are not visible

### ISSUE THREAD

**Issue by mrceresa** [bcn-medtech/reImagineClient#32]
**Describe the bug**
Since ddbf911f3c8e4402a53da3e7065c803e1c4b7897 a form is available in the anonimizer to add metadata to the upload. The title and description of the form are not well visible. Probably we need to fix the style.

**Expected behavior**
Title and description should be in white 

**Screenshots**
<img width="836" alt="Screenshot 2020-05-06 at 19 55 23" src="https://user-images.githubusercontent.com/524047/81211430-a8bc3700-8fd3-11ea-8270-bea980dfe00b.png">

**Comment by carlosym** [comment]
User interface style has been improved, also now the user is can open the finder just clicking the folder icon of the different button folders of the User interface
