### ISSUE TITLE
[BUG] Annotations are lost if put before anonimization

### ISSUE THREAD

**Issue by mrceresa** [bcn-medtech/reImagineClient#33]
**Describe the bug**
If I put the annotations before starting the anonimization, they are lost and the uploaded metadata.json contains only "null"
 
**Expected behavior**
Annotations should be maintained independently from the anonimization process 

**Additional context**
Annotations should be retrieved from the state.formData of the form so we ensure that we always capture the latest information the user has introduced. Trying to sync between forms is not a good idea IMO

**Comment by mrceresa** [comment]
Okay I looked better at the code, I think the problem is just that the form state is not saved when the main anonimizer component resets. It is a bit unfortunate because the user expects that whatever he put there would remain.... I think we should either save that in the main state or just disable the annotations until we are sure we will not lose user input

**Comment by carlosym** [comment]
You are right, I'll do it.

**Comment by carlosym** [comment]
Solved adding the note to the root page state
